logLevel = "debug"

[test]
root = "./tests"
coverage = true
coverageThreshold = { line = 0.7, function = 0.8, statement = 0.9 }
coverageDir = "./coverage"
coverageReporter  = ["text", "lcov"]
rerunEach = 1
coveragePathIgnorePatterns = ["/node_modules/", "/tests/fixtures/", "dev/**/*.ts", "examples/**/*.ts"]
